services:
  api:
    build: ./model_app
    ports:
      - "8000:8000"
    networks:
      - app_network
  
  ui:
    build: ./ui_app
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge